---
title: Ziel端bung
hero_image: images/banner.png
description: Zeichne mit Python eine Zielscheibe und erziele Punkte, indem Du sie mit Pfeilen triffst
meta_title: Python Programmierprojekte f端r Kinder und Jugendliche | Ziel端bung
meta_description: Lerne Python mit den Programmierprojekten der Raspberry Pi Foundation f端r Kinder und Jugendliche. Zeichne mit Python eine Zielscheibe und erziele Punkte, indem Du sie mit Pfeilen triffst.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - title: Das wirst du machen
  - title: Erstelle einen Hintergrund
  - title: Zeichne deine Zielscheibe
    completion:
      - engaged
  - title: Feuere deinen Pfeil ab
  - title: Punkten
    completion:
      - internal
  - title: Kurzes Quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Verbessere Dein Projekt
  - title: Wie geht es weiter?
