---
title: Praktyka docelowa
hero_image: images/banner.png
description: Użyj Pythona, aby narysować cel i zdobywać punkty, uderzając go strzałkami
meta_title: Projekty kodowania w Pythonie dla dzieci i młodzieży | Praktyka docelowa
meta_description: Naucz się języka Python z projektami programistycznymi Fundacji Raspberry Pi dla dzieci i młodzieży. Użyj Pythona, aby narysować cel i zdobywać punkty, uderzając go strzałkami.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: What you will make
  - 
    title: Draw the grass
  - 
    title: Narysuj swój cel
    completion:
      - engaged
  - 
    title: Add an arrow
  - 
    title: What colour did you hit?
  - 
    title: Score points
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Challenge
    challenge: true
  - 
    title: What can you do now?
