---
title: Tir sur cible
hero_image: images/banner.png
description: Utilise Python pour dessiner une cible et marquer des points en la frappant avec des flèches
meta_title: Projets de codage Python pour enfants et adolescents | Tir sur cible
meta_description: Apprends le langage Python avec les projets de codage de la Raspberry Pi Foundation pour les enfants et les adolescents. Utilise Python pour dessiner une cible et marquer des points en l'atteignant avec des flèches.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Ce que tu vas faire
  - 
    title: Créer un arrière-plan
  - 
    title: Dessiner ta cible
    completion:
      - engaged
  - 
    title: Tirer la flèche
  - 
    title: Marquer des points
  - 
    title: Questionnaire rapide
    completion:
      - external
  - 
    title: Améliorer ton projet
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Et ensuite ?
    challenge: true
  - 
    title: What can you do now?
