---
title: Tir sur cible
hero_image: images/banner.png
description: Utilise Python pour dessiner une cible et marquer des points en l'atteignant avec des flèches
meta_title: Projets de codage Python pour enfants et adolescents | Tir sur cible
meta_description: Apprends le langage Python avec les projets de codage de la Raspberry Pi Foundation pour les enfants et les adolescents. Utilise Python pour dessiner une cible et marquer des points en l'atteignant avec des flèches.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Ce que tu vas faire
  - 
    title: Dessiner l'herbe
  - 
    title: Dessiner ta cible
    completion:
      - engaged
  - 
    title: Ajouter une flèche
  - 
    title: Quelle est la couleur atteinte ?
  - 
    title: Marquer des points
    completion:
      - internal
  - 
    title: Questionnaire rapide
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Défi
    challenge: true
  - 
    title: Que peux-tu faire maintenant ?
