---
title: Allenamento di tiro al bersaglio
hero_image: images/banner.png
description: Usa Python per disegnare un bersaglio e fare punti colpendolo con le frecce
meta_title: Progetti di programmazione in Python per bambini e ragazzi | Allenamento di tiro al bersaglio
meta_description: Impara Python con i progetti di codifica della Raspberry Pi Foundation per bambini e adolescenti. Usa Python per disegnare un bersaglio e segnare punti colpendolo con le frecce.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - title: Quello che farai
  - title: Crea uno sfondo
  - title: Disegna il tuo bersaglio
    completion:
      - engaged
  - title: Scocca la tua freccia
  - title: Punteggio
    completion:
      - internal
  - title: Quiz veloce
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Migliora il tuo progetto